---
title: "recidivism"
author: "thibault FUCHEZ"
date: "13/05/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/arkan/Desktop/Memoire-M1/applications_R")
```

```{r}
source("functions_UC.R")
```

# prepa datas

```{r}
recid <-
  read.csv(
    "recidivism.csv",
    header = TRUE,
    sep = ",",
    stringsAsFactors = T
  )
data <-   read_csv("recidivism.csv")
```

```{r}
#temps passé en prison 

data$time_jailed <- data[,"c_jail_out"] - data[,"c_jail_in"]
recid$time_jailed <- data$time_jailed
```

```{r}
recid<- recid[,c("sex","age_cat","race","juv_fel_count","juv_misd_count","juv_other_count", "priors_count","c_charge_degree","time_jailed","is_recid")]
```

```{r}
recid$time_jailed <- recid$time_jailed / (60*24)
recid$time_jailed <- as.difftime(unlist(recid$time_jailed), units = "days")
recid$time_jailed <- abs(recid$time_jailed)
```

```{r}
sum(is.na(recid$time_jailed))
sum(is.na(recid))
recid <- na.omit(recid)
recid$is_recid <- as.factor(recid$is_recid)
```

```{r}
recid <- recid[,c(10, 1:9 )]
```

# first models

```{r}
datRecid <- split_standard(data =  recid, y =  "is_recid", mod = "standard")
```

```{r}
Modrecid <- models(y = "is_recid", data = datRecid$train,
                   priors(dat = datRecid$train, "is_recid"))
```

```{r}
PredRec1 <- predictions(models = Modrecid, datas = datRecid)
```

```{r}
KablesPerf(pred = PredRec1, dat = datRecid$test, y = "is_recid")
```

```{r}
par(mfrow=c(1,1))
AllRoc(predic = PredRec1, dataCl = datRecid$test$is_recid)
```

# remedies

## Datas prepocessing : 

```{r}
DatRecUS <- resamp_res(recid, mod = "US")
```

```{r}
Resamptest <- upSample(recid[,-1], recid[,1])

```

# Notes 

Voc: 

battery : coups et blessure
degree charge : F fellony (crime et délit) / M midemeanor (infraction)
priors : antécédents

tps passé en prision : 

Remplacer NA par moyenne du tps passé. mettre en valeur absolur car parfois inversé. 


